sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t vittalharishtk/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vittalharishtk/docker-react npm run test